# 0. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
import torch

x = torch.rand(7, 7)
print(x)

tensor([[0.4787, 0.6151, 0.7030, 0.9746, 0.8047, 0.7300, 0.5381],
        [0.0522, 0.4441, 0.8756, 0.4297, 0.0392, 0.6014, 0.6930],
        [0.0052, 0.0856, 0.0872, 0.8603, 0.3633, 0.6797, 0.0318],
        [0.2006, 0.8841, 0.6430, 0.3812, 0.4086, 0.8208, 0.4238],
        [0.3390, 0.2634, 0.6744, 0.2726, 0.6084, 0.0591, 0.5190],
        [0.7007, 0.0029, 0.6301, 0.2023, 0.7181, 0.3657, 0.6928],
        [0.8596, 0.7671, 0.9807, 0.3829, 0.4760, 0.6387, 0.2778]])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [2]:
y = torch.rand(1, 7)

multiplicacao = torch.matmul(x, y.T)
print(multiplicacao) 

tensor([[2.7387],
        [1.4319],
        [1.6892],
        [1.9618],
        [1.2598],
        [1.5540],
        [1.7683]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [3]:
torch.manual_seed(0)

x1 = torch.rand(7, 7)
x2 = torch.rand(1, 7)

mult = torch.matmul(x1, x2.T)
print(mult)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [10]:
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [14]:
torch.manual_seed(1234)

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f'device: {device}')

x = torch.rand(2, 3).to(device)
y = torch.rand(2, 3).to(device)

x, y

device: cpu


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]]))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [18]:
z = torch.matmul(x, y.T)
z, z.shape


(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]]),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [19]:
max = torch.max(z)

min = torch.min(z)

max, min

(tensor(0.5617), tensor(0.3647))

### 9. Find the maximum and minimum index values of the output of 7.

In [20]:
max_val = torch.argmax(z)

min_val = torch.argmin(z)

max_val, min_val

(tensor(3), tensor(0))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [22]:
torch.manual_seed(7)

w = torch.rand(size=(1, 1, 1, 10))

# remover dimensões unicas
f = w.squeeze()

print(w, w.shape)
print(f, f.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
